DROP TABLE IF EXISTS locations;

CREATE TABLE locations (
  id SERIAL PRIMARY KEY NOT NULL,
  search_query VARCHAR(255) NOT NULL,
  formatted_query VARCHAR(255) NOT NULL,
  latitude INTEGER NOT NULL,
  longitude INTEGER NOT NULL
);
DROP TABLE IF EXISTS people;
CREATE TABLE people (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255),
  role VARCHAR(255)
);
